baseURL = ""
languageCode = "en-us"
title = "Zillion Flavours"
theme = "restaurant hugo"
summaryLength = "10"
paginate = 4
themesDir = "themes"
publishDir = "public"

[params]
logo = "images/LOGO horizontal.png"
author = "Themefisher"
description = "This is meta description"
google_analitycs_id = "Your ID"
main_sections = [ "post" ]
copyright = "Copyright &copy; 2021 Designed & Developed by [Techwork Professionals](https://techworkpro.com)"

[[params.plugins.css]]
URL = "css/bootstrap.min.css"

[[params.plugins.css]]
URL = "css/slick.css"

[[params.plugins.css]]
URL = "css/font-awesome.min.css"

[[params.plugins.css]]
URL = "css/animate.min.css"

[[params.plugins.css]]
URL = "css/venobox.css"

[[params.plugins.css]]
URL = "css/main.css"

[[params.plugins.css]]
URL = "css/responsive.css"

[[params.plugins.js]]
URL = "js/jquery.min.js"

[[params.plugins.js]]
URL = "js/bootstrap.min.js"

[[params.plugins.js]]
URL = "js/slick.min.js"

[[params.plugins.js]]
URL = "js/wow.min.js"

[[params.plugins.js]]
URL = "js/venobox.min.js"

[[params.plugins.js]]
URL = "js/main.js"

  [params.preloader]
  enable = false
  preloader = ""

  [params.footer]
  enable = true
  contactInfoTitle = "CONTACT <span>INFO</span> "
  blogTitle = "LATEST <span>Items</span>"
  galleryTitle = "PHOTO <span>STREAM</span>"
  socialTitle = "Follow <span>US</span>"

    [[params.footer.contactItem]]
    title = "Telephone"
    icon = "fa fa-phone"
    content = "+852 5260 8484"

    [[params.footer.contactItem]]
    title = "Address"
    icon = "fa fa-map-marker"
    content = "Shop 128 A3, 1/F., Kings Wing Plaza - 2, 1 On Kwan Rd., Shek Mun, Shatin, N.T., Hong Kong"

    [[params.footer.contactItem]]
    title = "E mail"
    icon = "fa fa-envelope"
    content = "info@zillionflavours.com"

    [[params.footer.gallery]]
    image = "images/slider/idli sambar.jpg"

    [[params.footer.gallery]]
    image = "images/slider/naan butter ckn.jpg"

    [[params.footer.gallery]]
    image = "images/slider/pathiri egg.jpg"

    [[params.footer.gallery]]
    image = "images/slider/porotta beef.jpg"

    [[params.footer.gallery]]
    image = "images/slider/porotta mutton.jpg"

    [[params.footer.gallery]]
    image = "images/slider/stringhpr veg korma.jpg"

    [[params.footer.socialLink]]
    icon = "facebook"
    link = "https://fb.com/shopzillionflavours"

    # [[params.footer.socialLink]]
    # icon = "twitter"
    # link = "https://fb.com/themefisher"

    # [[params.footer.socialLink]]
    # icon = "dribbble"
    # link = "https://fb.com/themefisher"

    [[params.footer.socialLink]]
    icon = "instagram"
    link = "https://www.instagram.com/zillionflavoursonline/"

[[menu.main]]
name = "Home"
URL = "hero-area"
weight = 1

[[menu.main]]
name = "About Us"
URL = "about-us"
weight = 2

[[menu.main]]
name = "Blog"
URL = "blog"
weight = 3

[[menu.main]]
name = "Price"
URL = "price"
weight = 4

[[menu.main]]
name = "News"
URL = "subscribe"
weight = 5

[[menu.main]]
name = "Contact Us"
URL = "contact-us"
weight = 6
